"""empty message

Revision ID: 71461529665d
Revises: 9c4c6f67af3c
Create Date: 2026-03-15 11:37:53.499853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71461529665d'
down_revision = '9c4c6f67af3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
